<?php

if ( ! defined( 'WPINC' ) ) {
	die;
}

class SRSB_Patterns {

	public function __construct() {
		add_action( 'init', array( $this, 'register_pattern_categories' ), 10 );
		add_action( 'init', array( $this, 'register_test_patterns' ), 11 );
	}

	public function register_pattern_categories() {
		register_block_pattern_category( 'simreact-heroes', array(
			'label' => __( 'SimReact – Heroes', 'simreact-site-builder' ),
		) );

		register_block_pattern_category( 'simreact-features', array(
			'label' => __( 'SimReact – Features', 'simreact-site-builder' ),
		) );

		register_block_pattern_category( 'simreact-ctas', array(
			'label' => __( 'SimReact – CTAs', 'simreact-site-builder' ),
		) );

		register_block_pattern_category( 'simreact-testimonials', array(
			'label' => __( 'SimReact – Testimonials', 'simreact-site-builder' ),
		) );

		register_block_pattern_category( 'simreact-structure', array(
			'label' => __( 'SimReact – Structure', 'simreact-site-builder' ),
		) );
	}

	public function register_test_patterns() {
		register_block_pattern(
			'simreact/test-hero',
			array(
				'title'      => __( 'Hero Test Pattern', 'simreact-site-builder' ),
				'description' => __( 'Test pattern for SimReact heroes', 'simreact-site-builder' ),
				'categories' => array( 'simreact-heroes' ),
				'content'    => '<!-- wp:group {"className":"srsb-test-hero"} -->
<!-- wp:heading -->Test Hero Section<!-- /wp:heading -->
<!-- wp:paragraph -->This is a placeholder hero block generated by the SimReact plugin.<!-- /wp:paragraph -->
<!-- /wp:group -->',
			)
		);

		register_block_pattern(
			'simreact/test-feature',
			array(
				'title'      => __( 'Feature Test Pattern', 'simreact-site-builder' ),
				'description' => __( 'Test pattern for SimReact features', 'simreact-site-builder' ),
				'categories' => array( 'simreact-features' ),
				'content'    => '<!-- wp:group {"className":"srsb-test-feature"} -->
<!-- wp:heading -->Test Feature Block<!-- /wp:heading -->
<!-- wp:paragraph -->This is a placeholder feature section.<!-- /wp:paragraph -->
<!-- /wp:group -->',
			)
		);
	}

}
